### ISSUE TITLE
Управление нагревателем

### ISSUE THREAD

**Issue by dimontau** [GyverLibs/GyverHTU21D#1]
Приветствую. Напишите как управлять нагревателем.

**Comment by GyverLibs** [comment]
Привет, об этом написано в уроках

**Comment by dimontau** [comment]
Можно ссылку, а то не могу найти. Очень нужно периодически включать подогрев иначе он глючит.

**Comment by GyverLibs** [comment]
https://alexgyver.ru/lessons/
